FROM golang:1.10.1-alpine
ADD https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 /usr/local/bin/dep
RUN apk --no-cache add libpcap-dev make gcc git libc-dev && \
    chmod 755 /usr/local/bin/dep
